Repository MissionBit/BAMPWebsite, pull requests merged in 2020-10, with the labels that each got.

#38 Delint CSS
  .stylelintrc.yaml
  style/base.css
  style/modules/box.css
  style/modules/btnLink.css
  style/modules/emailForm.css
  style/modules/event.css
  style/modules/faq.css
  style/modules/infoCard.css
  style/modules/muralThumbnail.css
  style/modules/pageHeader.css
  style/modules/program.css
  style/modules/sectionHeading.css
Labels: tooling

#36 Add .press module
  storybook/index.html
  style/index.css
  style/modules/press.css
Labels: module

#40 Use color variables everywhere
  storybook/style.css
  style/index.css
  style/modules/box.css
  style/modules/btnLink.css
  style/modules/emailForm.css
  style/modules/event.css
  style/modules/faq.css
  style/modules/infoCard.css
  style/modules/missionStatement.css
  style/modules/muralThumbnail.css
  style/modules/navModal.css
  style/modules/pageHeader.css
  style/modules/press.css
  style/modules/program.css
  style/modules/sectionHeading.css
  style/modules/subFooter.css
  style/modules/teamMember.css
  style/modules/testimonial.css
  style/variables.css
Labels: cleanup

#35 Add .header module
  images/logo-mini-color.svg
  images/logo-mini-wireframe.svg
  script.js
  storybook/index.html
  style/index.css
  style/modules/header.css
  style/modules/navModal.css
Labels: module

#32 Add .footer module
  storybook/index.html
  style/index.css
  style/modules/btnLink.css
  style/modules/emailForm.css
  style/modules/footer.css
Labels: module

#50 Master cleanup
  .stylelintrc.yaml
  scripts/header.js
  scripts/index.js
  storybook/index.html
  style/modules/header.css
  style/modules/navModal.css
  style/modules/press.css
Labels: bug, cleanup
