Repository MissionBit/BAMPWebsite, pull requests merged in 2020-11, with the labels that each got.

#45 Add .muralModal module
  images/calendar.svg
  images/map-marker.svg
  images/palette.svg
  storybook/index.html
  style/base.css
  style/index.css
  style/modules/muralModal.css
Labels: module

#55 Sort storybook items dynamically
  storybook/index.html
  storybook/script.js
Labels: tooling

#54 Finish replacing color literals with CSS variables
  storybook/style.css
  style/base.css
  style/modules/box.css
  style/modules/emailForm.css
  style/modules/faq.css
  style/modules/footer.css
  style/modules/missionStatement.css
  style/modules/navModal.css
  style/modules/press.css
  style/modules/subFooter.css
  style/modules/teamMember.css
  style/modules/testimonial.css
  style/variables.css
Labels: cleanup

#60 Add mural.js for opening and closing mural modals
  scripts/index.js
  scripts/mural.js
  storybook/index.html
  style/layout.css
  style/modules/muralModal.css
Labels: work in progress
