Repository MissionBit/BAMPWebsite, pull requests merged in 2021-01, with the labels that each got.

#72 Programs Page
  images/programs/05CAA216-6086-4FFE-ACC3-A652DE4FFE96.JPG
  images/programs/1FEAC200-D3B1-4C28-8E12-EE667988F65A.JPG
  images/programs/2BDD79D7-9C8B-4453-933E-5EDB7F600CBD.JPG
  images/programs/4ACADCBD-3E38-4DEE-983C-9A7D66F9E966.JPG
  images/programs/4DB887FF-71EA-481F-955D-9E4C9322FE2F.JPG
  images/programs/6C00BC14-2041-4464-A6EA-9964E1B8AB47.JPG
  images/programs/6CCF2324-A9B7-456E-9DD1-6903567CC075.JPG
  images/programs/6EAC3A22-DA68-4C67-A5A3-FD2B086FA837.JPG
  images/programs/7F9772D7-78FF-4255-A933-53B2784D2389.JPG
  images/programs/8ACB8A4A-51DE-4885-BF80-C2625415A3EE.JPG
  images/programs/9D6FC2D9-A0FC-432D-BA71-142BA31C4A8D.JPG
  images/programs/9D732427-0162-48DE-A866-FAAC7E9FCD58.JPG
  programs.html
  storybook/index.html
  style/layout.css
  style/modules/fixedRatio.css
  style/modules/program.css
Labels: page

#83 Events Page
  events.html
  images/events/2BDD79D7-9C8B-4453-933E-5EDB7F600CBD.JPG
  images/events/473EC4D2-AE4E-4305-B343-B10198E8C615.JPG
  images/events/51AB214F-6B94-49DE-A849-1772EDFD7346.JPG
  images/events/6C00BC14-2041-4464-A6EA-9964E1B8AB47.JPG
  images/events/7F9772D7-78FF-4255-A933-53B2784D2389.JPG
  images/events/B0FF38D0-EFEF-413E-BAF5-BF12D02B2D70.JPG
  images/events/E4661E71-6AC0-4782-BE2E-ADADFDC997A5.JPG
  images/events/FAF4A214-4C57-40D5-A6B5-4C71BD66BE8B.JPG
  images/events/d45a2e_27aca9bed65640f79fc0e916138968a3~mv2.jpg
  style/layout.css
Labels: page

#84 Add .muralGallery module for hiding and showing
  scripts/index.js
  scripts/instaFeed.js
  scripts/muralGallery.js
  storybook/index.html
  storybook/style.css
  style/index.css
  style/modules/muralGallery.css
Labels: module

#98 Add testimonial carousel (and use Siema within .carousel)
  about_us.html
  artwork.html
  events.html
  get_involved.html
  index.html
  programs.html
  scripts/carousel.js
  scripts/index.js
  scripts/testimonials.js
  scripts/vendor/siemaWithDots.js
  services.html
  storybook/index.html
  style/layout.css
  style/modules/carousel.css
  style/modules/header.css
  style/modules/muralGallery.css
  style/modules/testimonial.css
Labels: work in progress

#117 Tweak text: metrics, copyright notice, events typo
  about_us.html
  artwork.html
  events.html
  get_involved.html
  index.html
  programs.html
  services.html
  storybook/index.html
Labels: cleanup
